In [1]:
import numpy as np
import pandas as pd
from IPython.display import display, HTML

def solve_transportation(costs, supply, demand):
    costs = np.array(costs, dtype=float)
    supply = list(supply)
    demand = list(demand)
    m, n = costs.shape
    
    # 1. Начальный опорный план (Метод северо-западного угла)
    allocation = np.zeros((m, n))
    i, j = 0, 0
    s, d = supply.copy(), demand.copy()
    while i < m and j < n:
        quantity = min(s[i], d[j])
        allocation[i, j] = quantity
        s[i] -= quantity
        d[j] -= quantity
        if s[i] == 0: i += 1
        elif d[j] == 0: j += 1
            
    iteration = 0
    while True:
        iteration += 1
        print(f"--- Итерация №{iteration} ---")
        display(pd.DataFrame(allocation, columns=[f'B{j+1}' for j in range(n)], 
                             index=[f'A{i+1}' for i in range(m)]))
        
        # 2. Нахождение потенциалов u и v
        u = [None] * m
        v = [None] * n
        u[0] = 0
        
        while None in u or None in v:
            for r in range(m):
                for c in range(n):
                    if allocation[r, c] > 0:
                        if u[r] is not None and v[c] is None:
                            v[c] = costs[r, c] - u[r]
                        elif v[c] is not None and u[r] is None:
                            u[r] = costs[r, c] - v[c]
        
        # 3. Оценки свободных клеток
        deltas = np.zeros((m, n))
        max_delta = -1e9
        entering_cell = None
        
        for r in range(m):
            for c in range(n):
                if allocation[r, c] == 0:
                    deltas[r, c] = u[r] + v[c] - costs[r, c]
                    if deltas[r, c] > max_delta:
                        max_delta = deltas[r, c]
                        entering_cell = (r, c)
        
        if max_delta <= 0:
            print("Оптимальный план найден!")
            break
            
        # 4. Построение цикла (упрощенная логика поиска цикла)
        # Для простоты примера используем поиск пути
        path = find_cycle(allocation, entering_cell)
        
        # 5. Пересчет плана
        plus_cells = path[0::2]
        minus_cells = path[1::2]
        theta = min(allocation[r, c] for r, c in minus_cells)
        
        for r, c in plus_cells: allocation[r, c] += theta
        for r, c in minus_cells: allocation[r, c] -= theta

    total_cost = np.sum(allocation * costs)
    print(f"\nИтоговая стоимость: {total_cost}")
    return allocation

def find_cycle(allocation, start_node):
    # Вспомогательная функция для поиска цикла (упрощенный поиск в графе)
    m, n = allocation.shape
    nodes = [(r, c) for r in range(m) for c in range(n) if allocation[r, c] > 0]
    nodes.append(start_node)
    
    def get_neighbors(node, axis):
        return [n for n in nodes if n[axis] == node[axis] and n != node]

    # Поиск пути через чередование строк и столбцов
    path = [start_node]
    def backtrack(curr, target_axis):
        for neighbor in get_neighbors(curr, target_axis):
            if neighbor == start_node and len(path) >= 4: return True
            if neighbor not in path:
                path.append(neighbor)
                if backtrack(neighbor, 1 - target_axis): return True
                path.pop()
        return False

    backtrack(start_node, 0)
    return path

# Данные для задачи
c = [[2, 3, 1], 
     [5, 4, 8], 
     [5, 6, 8]]
s = [20, 30, 25]
d = [15, 25, 35]

result = solve_transportation(c, s, d)

--- Итерация №1 ---

      B1    B2    B3
A1  15.0   5.0   0.0
A2   0.0  20.0  10.0
A3   0.0   0.0  25.0

--- Итерация №2 ---

      B1    B2    B3
A1  15.0   0.0   5.0
A2   0.0  25.0   5.0
A3   0.0   0.0  25.0

--- Итерация №3 ---

      B1    B2    B3
A1  10.0   0.0  10.0
A2   5.0  25.0   0.0
A3   0.0   0.0  25.0

--- Итерация №4 ---

      B1    B2    B3
A1   0.0   0.0  20.0
A2   5.0  25.0   0.0
A3  10.0   0.0  15.0

Оптимальный план найден!

Итоговая стоимость: 315.0

In [2]:
import pandas as pd
import numpy as np
import copy

def vogel_approximation_method(supply, demand, costs):
    s = copy.deepcopy(supply)
    d = copy.deepcopy(demand)
    c = copy.deepcopy(costs)
    
    n = len(s)
    m = len(d)
    
    # Результирующая матрица перевозок
    allocation = np.zeros((n, m))
    
    # Для визуализации итераций
    rows_active = list(range(n))
    cols_active = list(range(m))
    
    iteration = 1
    
    while len(rows_active) > 0 and len(cols_active) > 0:
        print(f"--- Итерация №{iteration} ---")
        
        # Вычисление штрафов
        row_penalties = []
        for i in rows_active:
            row_costs = sorted([c[i][j] for j in cols_active])
            penalty = row_costs[1] - row_costs[0] if len(row_costs) > 1 else row_costs[0]
            row_penalties.append((penalty, i))
            
        col_penalties = []
        for j in cols_active:
            col_costs = sorted([c[i][j] for i in rows_active])
            penalty = col_costs[1] - col_costs[0] if len(col_costs) > 1 else col_costs[0]
            col_penalties.append((penalty, j))
            
        # Находим максимальный штраф
        max_row_p = max(row_penalties, key=lambda x: x[0])
        max_col_p = max(col_penalties, key=lambda x: x[0])
        
        if max_row_p[0] >= max_col_p[0]:
            row_idx = max_row_p[1]
            # Ищем минимальную стоимость в этой строке
            min_cost_val = float('inf')
            col_idx = -1
            for j in cols_active:
                if c[row_idx][j] < min_cost_val:
                    min_cost_val = c[row_idx][j]
                    col_idx = j
        else:
            col_idx = max_col_p[1]
            # Ищем минимальную стоимость в этом столбце
            min_cost_val = float('inf')
            row_idx = -1
            for i in rows_active:
                if c[i][col_idx] < min_cost_val:
                    min_cost_val = c[i][col_idx]
                    row_idx = i
        
        # Распределение ресурса
        quantity = min(s[row_idx], d[col_idx])
        allocation[row_idx][col_idx] = quantity
        s[row_idx] -= quantity
        d[col_idx] -= quantity
        
        # Вывод текущего состояния
        df_display = pd.DataFrame(allocation, 
                                  index=[f'S{i+1}' for i in range(n)], 
                                  columns=[f'D{j+1}' for j in range(m)])
        print(df_display)
        print(f"Выбрана ячейка ({row_idx+1}, {col_idx+1}), объем: {quantity}")
        print("-" * 30)
        
        # Удаление строк/столбцов
        if s[row_idx] == 0:
            rows_active.remove(row_idx)
        elif d[col_idx] == 0:
            cols_active.remove(col_idx)
            
        iteration += 1
        
    total_cost = np.sum(allocation * costs)
    return allocation, total_cost

# Данные примера
supply = [50, 70, 30]
demand = [30, 60, 60]
costs = np.array([
    [2, 7, 4],
    [3, 3, 1],
    [5, 4, 7]
])

# Проверка на сбалансированность (закрытая задача)
if sum(supply) != sum(demand):
    print("Задача несбалансирована! Добавьте фиктивного поставщика/потребителя.")
else:
    final_alloc, total_cost = vogel_approximation_method(supply, demand, costs)
    print("\nИТОГОВАЯ ТАБЛИЦА ПЕРЕВОЗОК:")
    print(pd.DataFrame(final_alloc))
    print(f"\nОбщая стоимость (Z): {total_cost}")

--- Итерация №1 ---
     D1   D2    D3
S1  0.0  0.0   0.0
S2  0.0  0.0  60.0
S3  0.0  0.0   0.0
Выбрана ячейка (2, 3), объем: 60
------------------------------
--- Итерация №2 ---
      D1   D2    D3
S1  30.0  0.0   0.0
S2   0.0  0.0  60.0
S3   0.0  0.0   0.0
Выбрана ячейка (1, 1), объем: 30
------------------------------
--- Итерация №3 ---
      D1    D2    D3
S1  30.0  20.0   0.0
S2   0.0   0.0  60.0
S3   0.0   0.0   0.0
Выбрана ячейка (1, 2), объем: 20
------------------------------
--- Итерация №4 ---
      D1    D2    D3
S1  30.0  20.0   0.0
S2   0.0   0.0  60.0
S3   0.0  30.0   0.0
Выбрана ячейка (3, 2), объем: 30
------------------------------
--- Итерация №5 ---
      D1    D2    D3
S1  30.0  20.0   0.0
S2   0.0  10.0  60.0
S3   0.0  30.0   0.0
Выбрана ячейка (2, 2), объем: 10
------------------------------

ИТОГОВАЯ ТАБЛИЦА ПЕРЕВОЗОК:
      0     1     2
0  30.0  20.0   0.0
1   0.0  10.0  60.0
2   0.0  30.0   0.0

Общая стоимость (Z): 410.0